### ISSUE TITLE
Create auth activity

### ISSUE THREAD

**Issue by anxdre** [ANMP-Final-Project/WaroengUjang#4]
- [x] create layout auth activity for sign in
<img width="210" alt="image" src="https://github.com/ANMP-Final-Project/WaroengUjang/assets/32446250/e6aade8f-dbdd-46f8-a140-1f247c9a0547">

- [x] create viewmodel
- [x] create auth verification manually to navigate home fragment
- [x] user must not able going back to this activity after login

**Comment by GhulamFadli** [comment]
done
