### ISSUE TITLE
Create menu & menu detail activity

### ISSUE THREAD

**Issue by anxdre** [ANMP-Final-Project/WaroengUjang#5]
<img width="450" alt="image" src="https://github.com/ANMP-Final-Project/WaroengUjang/assets/32446250/7669cb1d-6345-4cb0-8cef-9ce23aaae943">

- [x] create recycler view
- [x] create recycler view item layout
- [x] data must be get from api
- [x] can redirect to detail and showing detail menu

**Comment by anxdre** [comment]
menu was done

**Comment by ZufarRachman** [comment]
okee
